name: lanternchat
description: "A simple, reliable one-to-one chat application focused on clean architecture, predictable state management, and real-time messaging."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.7
  flutter: ">=3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # Style
  cupertino_icons: ^1.0.8
  # Firebase
  firebase_core: ^4.3.0
  firebase_database: ^12.1.1
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  # App Level
  flutter_launcher_icons: ^0.14.4
#  flutter_riverpod: ^3.2.0
  flutter_riverpod: ^2.5.1
  google_sign_in: ^7.2.0
  go_router: ^17.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  riverpod_lint: ^2.6.3
  custom_lint: ^0.7.6
#  riverpod_lint: ^3.1.2


flutter:

  uses-material-design: true
  assets:
    - assets/icons/main/lantern_icon.png




